### ISSUE TITLE
On line 20 getblock is a Problem

### ISSUE THREAD

**Issue by DragonfireHD** [BajanVlogs/RedStonePMMP#1]
Because my server kicked me from game

**Comment by DragonfireHD** [comment]
getBlockAgainst() is the right placemenf

**Comment by DragonfireHD** [comment]
use pocketmine\level\Level; is not more that name it is world world

**Comment by OfficialLilKev** [comment]
let me know if this issue is fixed with the new update id also be checking whatever issues you make have proper grammer for I can understand
