### ISSUE TITLE
Why use API 4 instead of API 5

### ISSUE THREAD

**Issue by Terpz710** [BajanVlogs/RedStonePMMP#2]
Are you intentionally using PM4? PM4 has been discontinued. Update to PM5 bro or don’t.

**Comment by OfficialLilKev** [comment]
its been fixed

**Comment by Terpz710** [comment]
I didn’t test the plugin myself but it looks like you are using pm 4 API. References to level when it got changed to world. As well as some of your other plugins. I suggest not using chat GPT since it gives out wrong/outdated answers.
